feat: add lit protocol encryption / decryption
RequestNetwork/invoicing-template pull request #67
Opened 2024-11-15 12:44 UTC by rodrigopavezi

Fixes #146

2024-11-15 13:53 UTC, rodrigopavezi commented on next.config.mjs
> +  },
It fails without it

2024-11-18 12:17 UTC, rodrigopavezi commented on utils/ethers.ts
> +}
Using wagmi code here

2024-11-18 12:18 UTC, rodrigopavezi commented on components/common/Navbar.tsx
> +  });
I will fix this one

2024-11-18 12:21 UTC, rodrigopavezi commented on utils/context.tsx
> +  const initializeRequestNetwork = (walletClient: any) => {
I will change to unknown

2024-11-18 12:23 UTC, rodrigopavezi commented on utils/context.tsx
> +      });
Could you create an issue for this as it is chore refactoring?

2024-11-18 12:25 UTC, rodrigopavezi commented on utils/context.tsx
> +  };
I will change

2024-11-18 12:27 UTC, rodrigopavezi commented on utils/context.tsx
> +                                            : undefined;
I will leave that change for another time

2024-11-18 12:30 UTC, rodrigopavezi commented on utils/context.tsx
> +  connectWalletToCypherProvider: (signer: any, walletAddress: string) => void;
I will change to unknown

2024-11-19 07:30 UTC, rodrigopavezi commented on utils/context.tsx
> +    signer: any,
that will break things

2024-11-25 20:49 UTC, aimensahnoun requested changes

2024-11-25 20:49 UTC, aimensahnoun commented on components/common/Navbar.tsx
> +  });
I agree with this

2024-12-02 19:34 UTC, rodrigopavezi commented on utils/context.tsx
> +          },
I will not change that now. Thanks

2024-12-03 06:08 UTC, MantisClone commented on utils/context.tsx
> +
Resovled as Outdated :hourglass_flowing_sand:

2024-12-03 06:09 UTC, MantisClone commented on utils/context.tsx
> +    }
Resolved as Outdated :hourglass_flowing_sand:

2024-12-03 11:34 UTC, rodrigopavezi commented on .env.example
> +#NEXT_PUBLIC_LIT_PROTOCOL_NETWORK=datil-dev
@MantisClone lit supports other chains besides Ethereum EVM.

2024-12-03 11:37 UTC, rodrigopavezi commented on components/common/Navbar.tsx
> +          // Add user notification here
Fixed it

2024-12-03 11:39 UTC, rodrigopavezi commented on utils/context.tsx
> +/** @format */
I thing it was from my Vscode fomatting. Removing

2024-12-03 11:40 UTC, rodrigopavezi commented on utils/context.tsx
> +          },
I will do that now

2024-12-03 19:59 UTC, rodrigopavezi commented on utils/context.tsx
> +          },
I am not refactor that now

2024-12-03 20:22 UTC, rodrigopavezi commented on utils/context.tsx
> +          },
I will not refactor this now

2024-12-03 20:43 UTC, MantisClone approved these changes

2024-12-03 20:43 UTC, MantisClone commented on README.md
> +| NEXT_PUBLIC_LIT_PROTOCOL_NETWORK               | Lit Protocol Network                 | ❌       |
1. NEXT_PUBLIC_GTM_ID is still a valid env var.
2. Please add NEXT_PUBLIC_REQUEST_NODE

2024-12-03 20:43 UTC, MantisClone commented on tsconfig.json
> +    "target": "ES2017"
Adding "target": "ES2017" is the only change in this file. Everything else in this file is a formatting change.

2024-12-04 03:00 UTC, merged